/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;


public class Form_Orders extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_Orders() {
        initComponents();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        TabOrder = new javax.swing.JTabbedPane();
        pnOrderForm = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        btnCreate_Order = new javax.swing.JButton();
        btnDelete_Order = new javax.swing.JButton();
        btnCancel_Order = new javax.swing.JButton();
        txtOrder_id = new javax.swing.JTextField();
        txtUser_id = new javax.swing.JTextField();
        txtUser_Payment_Method = new javax.swing.JTextField();
        txtAddress_id = new javax.swing.JTextField();
        txtTotal_Amount = new javax.swing.JTextField();
        rdoPaid = new javax.swing.JRadioButton();
        rdoPending = new javax.swing.JRadioButton();
        btnUpdate_Order1 = new javax.swing.JButton();
        pnOrderTable = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        txtFind_Order = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        pnOrderDetailsForm = new javax.swing.JPanel();
        pnAddressForm_list2 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        btnCreate_Order_detail = new javax.swing.JButton();
        btnDelete_Order_Detail = new javax.swing.JButton();
        btnCancel_Order_detail = new javax.swing.JButton();
        txtOderDetail_id = new javax.swing.JTextField();
        txtOrder_ID = new javax.swing.JTextField();
        txtProduct_Item_id = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice_Order_detail = new javax.swing.JPasswordField();
        btnUpdate_Order_Detail1 = new javax.swing.JButton();
        pnOrderDetailTable = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        txtFind_Order_detail = new javax.swing.JTextField();
        jButton32 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblOrder_detail = new javax.swing.JTable();
        jLabel92 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel5.setVerifyInputWhenFocusTarget(false);

        pnOrderForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Order Form");

        jLabel42.setText("Please fill all the information.");

        jLabel44.setText("ID");

        jLabel49.setText("User ID");

        jLabel50.setText("User Payment Method ID");

        jLabel53.setText("Address ID");

        jLabel54.setText("Total Amount");

        jLabel63.setText("Order Status");

        btnCreate_Order.setBackground(new java.awt.Color(0, 102, 102));
        btnCreate_Order.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreate_Order.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate_Order.setText("Create");
        btnCreate_Order.setBorderPainted(false);

        btnDelete_Order.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete_Order.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete_Order.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete_Order.setText("Delete");
        btnDelete_Order.setBorderPainted(false);

        btnCancel_Order.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel_Order.setText("Cancel");

        txtOrder_id.setEditable(false);

        rdoPaid.setSelected(true);
        rdoPaid.setText("Paid");

        rdoPending.setText("Pending");

        btnUpdate_Order1.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate_Order1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate_Order1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate_Order1.setText("Update");
        btnUpdate_Order1.setBorderPainted(false);

        javax.swing.GroupLayout pnOrderFormLayout = new javax.swing.GroupLayout(pnOrderForm);
        pnOrderForm.setLayout(pnOrderFormLayout);
        pnOrderFormLayout.setHorizontalGroup(
            pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderFormLayout.createSequentialGroup()
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnOrderFormLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(jLabel53)
                            .addComponent(jLabel50)
                            .addComponent(jLabel49)
                            .addComponent(jLabel44)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addGroup(pnOrderFormLayout.createSequentialGroup()
                                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCreate_Order)
                                    .addComponent(jLabel63))
                                .addGap(54, 54, 54)
                                .addComponent(btnUpdate_Order1)
                                .addGap(54, 54, 54)
                                .addComponent(btnDelete_Order)
                                .addGap(58, 58, 58)
                                .addComponent(btnCancel_Order)))
                        .addGap(0, 443, Short.MAX_VALUE))
                    .addGroup(pnOrderFormLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnOrderFormLayout.createSequentialGroup()
                                .addComponent(rdoPaid)
                                .addGap(41, 41, 41)
                                .addComponent(rdoPending)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtUser_id)
                            .addComponent(txtUser_Payment_Method)
                            .addComponent(txtAddress_id)
                            .addComponent(txtOrder_id, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotal_Amount))))
                .addContainerGap())
        );
        pnOrderFormLayout.setVerticalGroup(
            pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderFormLayout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGap(14, 14, 14)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtOrder_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(txtUser_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser_Payment_Method, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(18, 18, 18)
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(txtTotal_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(rdoPaid)
                    .addComponent(rdoPending))
                .addGap(50, 50, 50)
                .addGroup(pnOrderFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel_Order)
                    .addComponent(btnDelete_Order)
                    .addComponent(btnCreate_Order)
                    .addComponent(btnUpdate_Order1))
                .addGap(116, 116, 116))
        );

        TabOrder.addTab("Order Form", pnOrderForm);

        pnOrderTable.setBackground(new java.awt.Color(255, 255, 255));

        jButton28.setBackground(new java.awt.Color(0, 102, 102));
        jButton28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("Search");
        jButton28.setBorderPainted(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel66.setText("Order Table");

        txtFind_Order.setText("Order ID");

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblOrder);

        javax.swing.GroupLayout pnOrderTableLayout = new javax.swing.GroupLayout(pnOrderTable);
        pnOrderTable.setLayout(pnOrderTableLayout);
        pnOrderTableLayout.setHorizontalGroup(
            pnOrderTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOrderTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnOrderTableLayout.createSequentialGroup()
                        .addComponent(txtFind_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnOrderTableLayout.createSequentialGroup()
                        .addComponent(jLabel66)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnOrderTableLayout.setVerticalGroup(
            pnOrderTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderTableLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel66)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnOrderTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind_Order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        TabOrder.addTab("Order Table", pnOrderTable);

        pnAddressForm_list2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel67.setBackground(new java.awt.Color(0, 102, 102));
        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel67.setText("Order Detail Form");

        jLabel68.setText("Please fill all the information.");

        jLabel69.setText("ID");

        jLabel70.setText("Order ID");

        jLabel71.setText("Product Item ID");

        jLabel72.setText("Quantity");

        jLabel73.setText("Price");

        btnCreate_Order_detail.setBackground(new java.awt.Color(0, 102, 102));
        btnCreate_Order_detail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreate_Order_detail.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate_Order_detail.setText("Create");
        btnCreate_Order_detail.setBorderPainted(false);

        btnDelete_Order_Detail.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete_Order_Detail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete_Order_Detail.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete_Order_Detail.setText("Delete");
        btnDelete_Order_Detail.setBorderPainted(false);

        btnCancel_Order_detail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel_Order_detail.setText("Cancel");
        btnCancel_Order_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_Order_detailActionPerformed(evt);
            }
        });

        txtOderDetail_id.setEditable(false);

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnUpdate_Order_Detail1.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate_Order_Detail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate_Order_Detail1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate_Order_Detail1.setText("Update");
        btnUpdate_Order_Detail1.setBorderPainted(false);

        javax.swing.GroupLayout pnAddressForm_list2Layout = new javax.swing.GroupLayout(pnAddressForm_list2);
        pnAddressForm_list2.setLayout(pnAddressForm_list2Layout);
        pnAddressForm_list2Layout.setHorizontalGroup(
            pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddressForm_list2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAddressForm_list2Layout.createSequentialGroup()
                        .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel73)
                            .addComponent(jLabel72)
                            .addComponent(jLabel71)
                            .addComponent(jLabel70)
                            .addComponent(jLabel69)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67))
                        .addGap(697, 697, 697))
                    .addComponent(txtOrder_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOderDetail_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduct_Item_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAddressForm_list2Layout.createSequentialGroup()
                        .addComponent(btnCreate_Order_detail)
                        .addGap(29, 29, 29)
                        .addComponent(btnUpdate_Order_Detail1)
                        .addGap(18, 18, 18)
                        .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnAddressForm_list2Layout.createSequentialGroup()
                                .addComponent(btnDelete_Order_Detail)
                                .addGap(24, 24, 24)
                                .addComponent(btnCancel_Order_detail))
                            .addComponent(txtPrice_Order_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 60, Short.MAX_VALUE))
        );
        pnAddressForm_list2Layout.setVerticalGroup(
            pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddressForm_list2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel68)
                .addGap(18, 18, 18)
                .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(txtOderDetail_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(txtOrder_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduct_Item_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71))
                .addGap(18, 18, 18)
                .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrice_Order_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnAddressForm_list2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate_Order_detail)
                    .addComponent(btnDelete_Order_Detail)
                    .addComponent(btnCancel_Order_detail)
                    .addComponent(btnUpdate_Order_Detail1))
                .addGap(143, 143, 143))
        );

        javax.swing.GroupLayout pnOrderDetailsFormLayout = new javax.swing.GroupLayout(pnOrderDetailsForm);
        pnOrderDetailsForm.setLayout(pnOrderDetailsFormLayout);
        pnOrderDetailsFormLayout.setHorizontalGroup(
            pnOrderDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderDetailsFormLayout.createSequentialGroup()
                .addComponent(pnAddressForm_list2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnOrderDetailsFormLayout.setVerticalGroup(
            pnOrderDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderDetailsFormLayout.createSequentialGroup()
                .addComponent(pnAddressForm_list2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabOrder.addTab("Order Detail Form", pnOrderDetailsForm);

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel76.setText("Order Detail Table");

        txtFind_Order_detail.setText("Order ID");
        txtFind_Order_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFind_Order_detailActionPerformed(evt);
            }
        });

        jButton32.setBackground(new java.awt.Color(0, 102, 102));
        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("Search");
        jButton32.setBorderPainted(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        tblOrder_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblOrder_detail);

        javax.swing.GroupLayout pnOrderDetailTableLayout = new javax.swing.GroupLayout(pnOrderDetailTable);
        pnOrderDetailTable.setLayout(pnOrderDetailTableLayout);
        pnOrderDetailTableLayout.setHorizontalGroup(
            pnOrderDetailTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderDetailTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnOrderDetailTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(pnOrderDetailTableLayout.createSequentialGroup()
                        .addGroup(pnOrderDetailTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel76)
                            .addGroup(pnOrderDetailTableLayout.createSequentialGroup()
                                .addComponent(txtFind_Order_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnOrderDetailTableLayout.setVerticalGroup(
            pnOrderDetailTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderDetailTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnOrderDetailTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind_Order_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        TabOrder.addTab("Order Detail Table", pnOrderDetailTable);

        jLabel92.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel92.setText("Orders");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel92)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TabOrder)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel101)
                    .addComponent(jLabel92))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void btnCancel_Order_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_Order_detailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel_Order_detailActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtFind_Order_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFind_Order_detailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFind_Order_detailActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabOrder;
    private javax.swing.JButton btnCancel_Order;
    private javax.swing.JButton btnCancel_Order_detail;
    private javax.swing.JButton btnCreate_Order;
    private javax.swing.JButton btnCreate_Order_detail;
    private javax.swing.JButton btnDelete_Order;
    private javax.swing.JButton btnDelete_Order_Detail;
    private javax.swing.JButton btnUpdate_Order1;
    private javax.swing.JButton btnUpdate_Order_Detail1;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton32;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnAddressForm_list2;
    private javax.swing.JPanel pnOrderDetailTable;
    private javax.swing.JPanel pnOrderDetailsForm;
    private javax.swing.JPanel pnOrderForm;
    private javax.swing.JPanel pnOrderTable;
    private javax.swing.JRadioButton rdoPaid;
    private javax.swing.JRadioButton rdoPending;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblOrder_detail;
    private javax.swing.JTextField txtAddress_id;
    private javax.swing.JTextField txtFind_Order;
    private javax.swing.JTextField txtFind_Order_detail;
    private javax.swing.JTextField txtOderDetail_id;
    private javax.swing.JTextField txtOrder_ID;
    private javax.swing.JTextField txtOrder_id;
    private javax.swing.JPasswordField txtPrice_Order_detail;
    private javax.swing.JTextField txtProduct_Item_id;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal_Amount;
    private javax.swing.JTextField txtUser_Payment_Method;
    private javax.swing.JTextField txtUser_id;
    // End of variables declaration//GEN-END:variables
}
